working with arrays in numpy

In [1]:
import numpy as np

In [2]:
mylist=[[1,2,3],[4,5,6],[7,8,9]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.random.rand(5)

array([0.68494314, 0.01879861, 0.25270496, 0.97072588, 0.52672181])

In [4]:
np.random.rand(4,4)

array([[0.23772731, 0.81880996, 0.45213845, 0.84026869],
       [0.69198644, 0.66267104, 0.30024815, 0.92387307],
       [0.25911962, 0.79878403, 0.30987246, 0.44579399],
       [0.86760772, 0.58095862, 0.64896729, 0.06705981]])

In [5]:
np.random.rand(4)

array([0.75119431, 0.1428495 , 0.6124127 , 0.1609919 ])

In [6]:
print(np.add(10,23))

33


In [7]:
print(np.power(2,3))

8


In [11]:
a=[2,4,5,7,3,4,8]
a.sort()
print(a)

[2, 3, 4, 4, 5, 7, 8]


In [13]:
a=[2,4,5,7,3,4,8]
np.sort(a)

array([2, 3, 4, 4, 5, 7, 8])

In [15]:

print(np.mean(a))

4.714285714285714


In [18]:
print(np.std(a))

1.979486637221574


working with pandas
